### ISSUE TITLE
Jenkins pipeline stage 'test iac-blueprint-builder' fails when triggered by a pull request commit

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/iac-blueprint-builder#14]
### Current behaviour
When a pull request is created and committed Jenkins build fails with current error:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/jenkins/.local/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/home/jenkins/.local/lib/python3.5/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "/home/jenkins/.local/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "/home/jenkins/.local/lib/python3.5/site-packages/pip/_internal/req/__init__.py", line 64, in install_given_reqs
    auto_confirm=True
  File "/home/jenkins/.local/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 675, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "/home/jenkins/.local/lib/python3.5/site-packages/pip/_internal/req/req_uninstall.py", line 545, in from_dist
    link_pointer, dist.project_name, dist.location)
AssertionError: Egg-link /home/jenkins/workspace/blueprint-builder_template_fixes does not match installed location of src (at /home/jenkins/workspace/iac-blueprint-builder_PR-11)
```

If Jenkins build is triggered manually afterwards it completes without errors.

### Expected behaviour 
Jenkins pipeline completes without errors.

**Comment by salonikyal** [comment]
Is this still an issue?
